name: tidewise-app

services:
  server:
    container_name: reason-server
    image: spg-registry.cn-hangzhou.cr.aliyuncs.com/spg/openspg-server@sha256:fe6708deef9ebb8da8da7b1cb643e83b827769a5be8811961311639aa1f2cb88
    restart: unless-stopped
    volumes:
      - ./overrides/kag/kag_thinker.yaml:/home/admin/miniconda3/lib/python3.10/site-packages/kag/solver/pipelineconf/kag_thinker.yaml:ro
    ports:
      - "127.0.0.1:8887:8887"
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8
    command:
      - java
      - -Dfile.encoding=UTF-8
      - -Xms2048m
      - -Xmx8192m
      - -jar
      - arks-sofaboot-0.0.1-SNAPSHOT-executable.jar
      - --server.repository.impl.jdbc.host=mysql
      - --server.repository.impl.jdbc.password=${OPENSPG_MYSQL_ROOT_PASSWORD:-openspg}
      - --builder.model.execute.num=20
      - --cloudext.graphstore.url=neo4j://neo4j:7687?user=${OPENSPG_NEO4J_USER:-neo4j}&password=${OPENSPG_NEO4J_PASSWORD:-neo4j@openspg}&database=neo4j
      - --cloudext.searchengine.url=neo4j://neo4j:7687?user=${OPENSPG_NEO4J_USER:-neo4j}&password=${OPENSPG_NEO4J_PASSWORD:-neo4j@openspg}&database=neo4j
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://127.0.0.1:8887']
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    networks: [tidewise-local]

networks:
  tidewise-local:
    external: true
    name: tidewise-local
